#cloud-config
users:
  - name: pelias
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaTzpPLj3ymF7botJpCac7CDHhokrAMXPHbIQhSwZFgXPBhQfo5HhWOsn9yLBZv+ITpUKl74h1CB/UQkNTWjZWwSr5bSCzWUCnalHVGIZrRnYz57uQYCJwLxDGjcvNiV9syLMPIiCuwggPXVG9P9AWhgKGBdVyWoeRuXsgrfy5ijim74sFxg9u88lpnU4wWZCiS4liB9yBNJYe2cavIwPIQsk4wrMtT64JJOJR3IlQus+shvGba4iX6Nzgle7P35UbT9b9FF1DeUyLpw4XsvVFe8A7naS2NDPb41d59QyqnW7ZyNVuA/tUjgS6tK0f8H4GT8jd9Mm4nmjFzsa1Rg5Vwhglv9XqZjPGdwYcMxuH6leHz8NdftF8hCneNIeVdOU6F0za7eDIBY0DMw6lRTJf9UptfC2Dhd/WyIN3RGm83356pIX4ZMnsLwrK15XOSAFoE45sFt7b9SS2m9ngmfkCZcmYmM4UoYkTA47ByvS0xQ94OB0v3nNChZz4tbw4SmjPlsHRbBi+FSpPB91v3BJgyiZmfiDRyA9MISor297AbQxVAsPxmTyEopS57zx3M7YxHe7By/A1ysrnYFotM6dyTO64CpuKJTRWDLRoyjK/+jGH+3p0CjCJXrA3bksvJG7GIWfWeIHBZiR83cgFMTHyGedrxcwG/l+dNWxo/aRkXw==
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
disable_root: true
package-update: true
package-upgrade: true
packages:
  - docker.io
  - docker-compose-plugin
runcmd:
  - 'runuser -l pelias -c "mkdir /home/pelias/geosearch"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && git clone https://github.com/NYCPlanning/labs-geosearch-docker.git ."'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && mkdir -p data/elasticsearch data/csv data/whosonfirst"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && echo "DATA_DIR=/home/pelias/geosearch/data" > .env"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && ./pelias compose pull"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && ./pelias elastic start"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && ./pelias elastic wait"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && ./pelias elastic create"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && ./pelias download wof"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && ./pelias download csv"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && ./pelias import csv"'
  - 'runuser -l pelias -c "cd /home/pelias/geosearch && ./pelias compose up"'
